version: 2.1

jobs:

  provsion-infrastructure:
    docker:
      - image: amazon/aws-cli

    steps:
      - checkout
      - run:
          name: Configure server
          command: |
            aws cloudformation deploy --template-file ec2.yml --stack-name web --region us-east-1
      - run:
          name: Configure server
          command: |
            yum install -y tar gzip
            echo "[web]" > inventory.txt
            echo "hello" >> inventory.txt
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is
          # taken to be the root directory of the workspace.
          root: .
          # Must be relative path from root
          paths:
            - inventory.txt

workflows:
  welcome:
    jobs:
      - provsion-infrastructure
      #